# Generated by Django 4.0.6 on 2022-12-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('semail', models.EmailField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('Branch', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=100)),
            ],
        ),
    ]
